pm uninstall --user 0 cn.wps.xiaomi.abroad.lite
pm uninstall --user 0 com.alibaba.aliexpresshd
pm uninstall --user 0 com.amazon.appmanager
pm uninstall --user 0 com.amazon.fv
pm uninstall --user 0 com.amazon.kindle
pm uninstall --user 0 com.amazon.mShop.android
pm uninstall --user 0 com.amazon.mShop.android.shopping
pm uninstall --user 0 com.amazon.mp3
pm uninstall --user 0 com.amazon.venezia
pm uninstall --user 0 com.android.backupconfirm
pm uninstall --user 0 com.android.bips
pm uninstall --user 0 com.android.bookmarkprovider
pm uninstall --user 0 com.android.browser
pm uninstall --user 0 com.android.dreams.basic
pm uninstall --user 0 com.android.dreams.phototable
pm uninstall --user 0 com.android.egg
pm uninstall --user 0 com.android.email
pm uninstall --user 0 com.android.exchange
pm uninstall --user 0 com.android.hotwordenrollment.okgoogle
pm uninstall --user 0 com.android.packageinstaller
pm uninstall --user 0 com.android.printspooler
pm uninstall --user 0 com.android.providers.partnerbookmarks
pm uninstall --user 0 com.android.providers.userdictionary
pm uninstall --user 0 com.android.sharedstoragebackup
pm uninstall --user 0 com.android.stk
pm uninstall --user 0 com.android.wallpaper.livepicker
pm uninstall --user 0 com.android.wallpaperbackup
pm uninstall --user 0 com.android.wallpapercropper
pm uninstall --user 0 com.audible.application
pm uninstall --user 0 com.block.puzzle.game.hippo.mi
pm uninstall --user 0 com.blurb.checkout
pm uninstall --user 0 com.booking
pm uninstall --user 0 com.cequint.ecid
pm uninstall --user 0 com.cnn.mobile.android.phone.edgepanel
pm uninstall --user 0 com.crazy.juicer.xm
pm uninstall --user 0 com.diotek.sec.lookup.dictionary
pm uninstall --user 0 com.dsi.ant.plugins.antplus
pm uninstall --user 0 com.dsi.ant.sample.acquirechannels
pm uninstall --user 0 com.dsi.ant.server
pm uninstall --user 0 com.dsi.ant.service.socket
pm uninstall --user 0 com.duokan.phone.remotecontroller
pm uninstall --user 0 com.enhance.gameservice
pm uninstall --user 0 com.facebook.appmanager
pm uninstall --user 0 com.facebook.katana
pm uninstall --user 0 com.facebook.services
pm uninstall --user 0 com.facebook.system
pm uninstall --user 0 com.flipboard.app
pm uninstall --user 0 com.flipboard.boxer.app
pm uninstall --user 0 com.google.android.apps.books
pm uninstall --user 0 com.google.android.apps.docs
pm uninstall --user 0 com.google.android.apps.magazines
pm uninstall --user 0 com.google.android.apps.plus
pm uninstall --user 0 com.google.android.apps.subscriptions.red
pm uninstall --user 0 com.google.android.apps.tachyon
pm uninstall --user 0 com.google.android.apps.youtube.music
pm uninstall --user 0 com.google.android.gm
pm uninstall --user 0 com.google.android.googlequicksearchbox
pm uninstall --user 0 com.google.android.marvin.talkback
pm uninstall --user 0 com.google.android.music
pm uninstall --user 0 com.google.android.printservice.recommendation
pm uninstall --user 0 com.google.android.projection.gearhead
pm uninstall --user 0 com.google.android.talk
pm uninstall --user 0 com.google.android.tts
pm uninstall --user 0 com.google.android.videos
pm uninstall --user 0 com.google.android.youtube
pm uninstall --user 0 com.google.ar.core
pm uninstall --user 0 com.google.vr.vrcore
pm uninstall --user 0 com.gotv.nflgamecenter.us.lite
pm uninstall --user 0 com.hancom.office.editor.hidden
pm uninstall --user 0 com.imdb.mobile
pm uninstall --user 0 com.infraware.polarisoffice5
pm uninstall --user 0 com.jewelsblast.ivygames.Adventure.free
pm uninstall --user 0 com.linkedin.android
pm uninstall --user 0 com.logame.eliminateintruder3d
pm uninstall --user 0 com.mi.android.globalFileexplorer
pm uninstall --user 0 com.mi.android.globalpersonalassistant
pm uninstall --user 0 com.mi.global.pocobbs
pm uninstall --user 0 com.mi.global.pocostore
pm uninstall --user 0 com.mi.globalbrowser
pm uninstall --user 0 com.mi.globalminusscreen
pm uninstall --user 0 com.micredit.in
pm uninstall --user 0 com.microsoft.appmanager
pm uninstall --user 0 com.microsoft.office.excel
pm uninstall --user 0 com.microsoft.office.officehubrow
pm uninstall --user 0 com.microsoft.office.outlook
pm uninstall --user 0 com.microsoft.office.powerpoint
pm uninstall --user 0 com.microsoft.office.word
pm uninstall --user 0 com.microsoft.skydrive
pm uninstall --user 0 com.milink.service
pm uninstall --user 0 com.mintgames.triplecrush.tile.fun
pm uninstall --user 0 com.mintgames.wordtrip
pm uninstall --user 0 com.mipay.wallet.id
pm uninstall --user 0 com.mipay.wallet.in
pm uninstall --user 0 com.miui.analytics
pm uninstall --user 0 com.miui.android.fashiongallery
pm uninstall --user 0 com.miui.audioeffect
pm uninstall --user 0 com.miui.audiomonitor
pm uninstall --user 0 com.miui.bugreport
pm uninstall --user 0 com.miui.carlink
pm uninstall --user 0 com.miui.cit
pm uninstall --user 0 com.miui.cloudbackup
pm uninstall --user 0 com.miui.cloudservice
pm uninstall --user 0 com.miui.cloudservice.sysbase
pm uninstall --user 0 com.miui.compass
pm uninstall --user 0 com.miui.contentcatcher
pm uninstall --user 0 com.miui.daemon
pm uninstall --user 0 com.miui.huanji
pm uninstall --user 0 com.miui.hybrid
pm uninstall --user 0 com.miui.hybrid.accessory
pm uninstall --user 0 com.miui.maintenancemode
pm uninstall --user 0 com.miui.mediaeditor
pm uninstall --user 0 com.miui.mediaviewer
pm uninstall --user 0 com.miui.micloudsync
pm uninstall --user 0 com.miui.miservice
pm uninstall --user 0 com.miui.mishare.connectivity
pm uninstall --user 0 com.miui.misound
pm uninstall --user 0 com.miui.msa.global
pm uninstall --user 0 com.miui.nextpay
pm uninstall --user 0 com.miui.notes
pm uninstall --user 0 com.miui.personalassistant
pm uninstall --user 0 com.miui.phrase
pm uninstall --user 0 com.miui.player
pm uninstall --user 0 com.miui.smsextra
pm uninstall --user 0 com.miui.systemAdSolution
pm uninstall --user 0 com.miui.touchassistant
pm uninstall --user 0 com.miui.translation.kingsoft
pm uninstall --user 0 com.miui.translation.xmcloud
pm uninstall --user 0 com.miui.translation.youdao
pm uninstall --user 0 com.miui.translationservice
pm uninstall --user 0 com.miui.userguide
pm uninstall --user 0 com.miui.videoplayer
pm uninstall --user 0 com.miui.voiceassist
pm uninstall --user 0 com.miui.voiceassistoverlay
pm uninstall --user 0 com.miui.voicetrigger
pm uninstall --user 0 com.miui.vsimcore
pm uninstall --user 0 com.miui.weather2
pm uninstall --user 0 com.miui.wmsvc
pm uninstall --user 0 com.miui.yellowpage
pm uninstall --user 0 com.mobeam.barcodeService
pm uninstall --user 0 com.mobiletools.systemhelper
pm uninstall --user 0 com.monotype.android.font.chococooky
pm uninstall --user 0 com.monotype.android.font.cooljazz
pm uninstall --user 0 com.monotype.android.font.foundation
pm uninstall --user 0 com.monotype.android.font.rosemary
pm uninstall --user 0 com.mygalaxy
pm uninstall --user 0 com.netflix.mediaclient
pm uninstall --user 0 com.netflix.partner.activation
pm uninstall --user 0 com.nf.snake
pm uninstall --user 0 com.nuance.swype.input
pm uninstall --user 0 com.opera.browser
pm uninstall --user 0 com.opera.max.oem
pm uninstall --user 0 com.opera.preinstall
pm uninstall --user 0 com.osp.app.signin
pm uninstall --user 0 com.policydm
pm uninstall --user 0 com.qti.qcc
pm uninstall --user 0 com.qualcomm.uimremoteserver
pm uninstall --user 0 com.sec.android.AutoPreconfig
pm uninstall --user 0 com.sec.android.Preconfig
pm uninstall --user 0 com.sec.android.RilServiceModeApp
pm uninstall --user 0 com.sec.android.app.DataCreate
pm uninstall --user 0 com.sec.android.app.SecSetupWizard
pm uninstall --user 0 com.sec.android.app.SmartClipEdgeService
pm uninstall --user 0 com.sec.android.app.apex
pm uninstall --user 0 com.sec.android.app.applinker
pm uninstall --user 0 com.sec.android.app.billing
pm uninstall --user 0 com.sec.android.app.bluetoothtest
pm uninstall --user 0 com.sec.android.app.chromecustomizations
pm uninstall --user 0 com.sec.android.app.desktoplauncher
pm uninstall --user 0 com.sec.android.app.dexonpc
pm uninstall --user 0 com.sec.android.app.factorykeystring
pm uninstall --user 0 com.sec.android.app.gamehub
pm uninstall --user 0 com.sec.android.app.hwmoduletest
pm uninstall --user 0 com.sec.android.app.kidshome
pm uninstall --user 0 com.sec.android.app.magnifier
pm uninstall --user 0 com.sec.android.app.myfiles
pm uninstall --user 0 com.sec.android.app.ocr
pm uninstall --user 0 com.sec.android.app.parser
pm uninstall --user 0 com.sec.android.app.personalization
pm uninstall --user 0 com.sec.android.app.popupcalculator
pm uninstall --user 0 com.sec.android.app.quicktool
pm uninstall --user 0 com.sec.android.app.ringtoneBR
pm uninstall --user 0 com.sec.android.app.safetyassurance
pm uninstall --user 0 com.sec.android.app.sbrowser
pm uninstall --user 0 com.sec.android.app.servicemodeapp
pm uninstall --user 0 com.sec.android.app.shealth
pm uninstall --user 0 com.sec.android.app.soundalive
pm uninstall --user 0 com.sec.android.app.sysscope
pm uninstall --user 0 com.sec.android.app.tfunlock
pm uninstall --user 0 com.sec.android.app.tourviewer
pm uninstall --user 0 com.sec.android.app.translator
pm uninstall --user 0 com.sec.android.app.ve.vebgm
pm uninstall --user 0 com.sec.android.app.wfdbroker
pm uninstall --user 0 com.sec.android.app.withtv
pm uninstall --user 0 com.sec.android.app.wlantest
pm uninstall --user 0 com.sec.android.cover.ledcover
pm uninstall --user 0 com.sec.android.daemonapp
pm uninstall --user 0 com.sec.android.desktopmode.uiservice
pm uninstall --user 0 com.sec.android.diagmonagent
pm uninstall --user 0 com.sec.android.easyMover
pm uninstall --user 0 com.sec.android.easyMover.Agent
pm uninstall --user 0 com.sec.android.easyonehand
pm uninstall --user 0 com.sec.android.emergencylauncher
pm uninstall --user 0 com.sec.android.mimage.avatarstickers
pm uninstall --user 0 com.sec.android.mimage.gear360editor
pm uninstall --user 0 com.sec.android.mimage.photoretouching
pm uninstall --user 0 com.sec.android.ofviewer
pm uninstall --user 0 com.sec.android.omc
pm uninstall --user 0 com.sec.android.preloadinstaller
pm uninstall --user 0 com.sec.android.provider.snote
pm uninstall --user 0 com.sec.android.providers.security
pm uninstall --user 0 com.sec.android.providers.tasks
pm uninstall --user 0 com.sec.android.sdhms
pm uninstall --user 0 com.sec.android.service.health
pm uninstall --user 0 com.sec.android.sidesync30
pm uninstall --user 0 com.sec.android.splitsound
pm uninstall --user 0 com.sec.android.uibcvirtualsoftkey
pm uninstall --user 0 com.sec.android.widgetapp.diotek.smemo
pm uninstall --user 0 com.sec.android.widgetapp.easymodecontactswidget
pm uninstall --user 0 com.sec.app.TransmitPowerService
pm uninstall --user 0 com.sec.automation
pm uninstall --user 0 com.sec.bcservice
pm uninstall --user 0 com.sec.downloadablekeystore
pm uninstall --user 0 com.sec.enterprise.knox.attestation
pm uninstall --user 0 com.sec.enterprise.knox.cloudmdm.smdms
pm uninstall --user 0 com.sec.enterprise.mdm.services.simpin
pm uninstall --user 0 com.sec.enterprise.mdm.vpn
pm uninstall --user 0 com.sec.epdgtestapp
pm uninstall --user 0 com.sec.everglades
pm uninstall --user 0 com.sec.everglades.update
pm uninstall --user 0 com.sec.factory
pm uninstall --user 0 com.sec.factory.camera
pm uninstall --user 0 com.sec.factory.iris.usercamera
pm uninstall --user 0 com.sec.hearingadjust
pm uninstall --user 0 com.sec.kidsplat.installer
pm uninstall --user 0 com.sec.knox.foldercontainer
pm uninstall --user 0 com.sec.knox.knoxsetupwizardclient
pm uninstall --user 0 com.sec.knox.switcher
pm uninstall --user 0 com.sec.location.nsflp2
pm uninstall --user 0 com.sec.mldapchecker
pm uninstall --user 0 com.sec.modem.settings
pm uninstall --user 0 com.sec.providers.assisteddialing
pm uninstall --user 0 com.sec.readershub
pm uninstall --user 0 com.sec.smartcard.manager
pm uninstall --user 0 com.sec.spen.flashannotate
pm uninstall --user 0 com.sec.spp.push
pm uninstall --user 0 com.sec.sve
pm uninstall --user 0 com.sec.usbsettings
pm uninstall --user 0 com.sec.vowifispg
pm uninstall --user 0 com.sec.yosemite.phone
pm uninstall --user 0 com.sem.factoryapp
pm uninstall --user 0 com.singtel.mysingtel
pm uninstall --user 0 com.skms.android.agent
pm uninstall --user 0 com.skype.raider
pm uninstall --user 0 com.sohu.inputmethod.sogou.xiaomi
pm uninstall --user 0 com.spotify.music
pm uninstall --user 0 com.sukhavati.gotoplaying.bubble.BubbleShooter.mint
pm uninstall --user 0 com.tencent.soter.soterserver
pm uninstall --user 0 com.test.LTEfunctionality
pm uninstall --user 0 com.touchtype.swiftkey
pm uninstall --user 0 com.tripadvisor.tripadvisor
pm uninstall --user 0 com.trustonic.tuiservice
pm uninstall --user 0 com.unionpay.tsmservice.mi
pm uninstall --user 0 com.vlingo.midas
pm uninstall --user 0 com.wssnps
pm uninstall --user 0 com.xiaomi.ab
pm uninstall --user 0 com.xiaomi.aiasst.service
pm uninstall --user 0 com.xiaomi.aiasst.vision
pm uninstall --user 0 com.xiaomi.bluetooth
pm uninstall --user 0 com.xiaomi.calendar
pm uninstall --user 0 com.xiaomi.gamecenter.sdk.service
pm uninstall --user 0 com.xiaomi.glgm
pm uninstall --user 0 com.xiaomi.gnss.polaris
pm uninstall --user 0 com.xiaomi.joyose
pm uninstall --user 0 com.xiaomi.mi_connect_service
pm uninstall --user 0 com.xiaomi.micloud.sdk
pm uninstall --user 0 com.xiaomi.midrop
pm uninstall --user 0 com.xiaomi.migameservice
pm uninstall --user 0 com.xiaomi.mipicks
pm uninstall --user 0 com.xiaomi.miplay_client
pm uninstall --user 0 com.xiaomi.mircs
pm uninstall --user 0 com.xiaomi.mirecycle
pm uninstall --user 0 com.xiaomi.mirror
pm uninstall --user 0 com.xiaomi.payment
pm uninstall --user 0 com.xiaomi.powerchecker
pm uninstall --user 0 com.xiaomi.simactivate.service
pm uninstall --user 0 com.xiaomi.smarthome
pm uninstall --user 0 com.xiaomi.xmsf
pm uninstall --user 0 com.xiaomi.xmsfkeeper
pm uninstall --user 0 com.zhiliaoapp.musically
pm uninstall --user 0 org.mipay.android.manager
echo " Debloat HyperOs Success!!!"