debloat() {
pm install-existing cn.wps.xiaomi.abroad.lite
pm install-existing com.alibaba.aliexpresshd
pm install-existing com.amazon.appmanager
pm install-existing com.amazon.fv
pm install-existing com.amazon.kindle
pm install-existing com.amazon.mShop.android
pm install-existing com.amazon.mShop.android.shopping
pm install-existing com.amazon.mp3
pm install-existing com.amazon.venezia
pm install-existing com.android.backupconfirm
pm install-existing com.android.bips
pm install-existing com.android.bookmarkprovider
pm install-existing com.android.browser
pm install-existing com.android.dreams.basic
pm install-existing com.android.dreams.phototable
pm install-existing com.android.egg
pm install-existing com.android.email
pm install-existing com.android.exchange
pm install-existing com.android.hotwordenrollment.okgoogle
pm install-existing com.android.packageinstaller
pm install-existing com.android.printspooler
pm install-existing com.android.providers.partnerbookmarks
pm install-existing com.android.providers.userdictionary
pm install-existing com.android.sharedstoragebackup
pm install-existing com.android.stk
pm install-existing com.android.wallpaper.livepicker
pm install-existing com.android.wallpaperbackup
pm install-existing com.android.wallpapercropper
pm install-existing com.audible.application
pm install-existing com.block.puzzle.game.hippo.mi
pm install-existing com.blurb.checkout
pm install-existing com.booking
pm install-existing com.cequint.ecid
pm install-existing com.cnn.mobile.android.phone.edgepanel
pm install-existing com.crazy.juicer.xm
pm install-existing com.diotek.sec.lookup.dictionary
pm install-existing com.dsi.ant.plugins.antplus
pm install-existing com.dsi.ant.sample.acquirechannels
pm install-existing com.dsi.ant.server
pm install-existing com.dsi.ant.service.socket
pm install-existing com.duokan.phone.remotecontroller
pm install-existing com.enhance.gameservice
pm install-existing com.facebook.appmanager
pm install-existing com.facebook.katana
pm install-existing com.facebook.services
pm install-existing com.facebook.system
pm install-existing com.flipboard.app
pm install-existing com.flipboard.boxer.app
pm install-existing com.google.android.apps.books
pm install-existing com.google.android.apps.docs
pm install-existing com.google.android.apps.magazines
pm install-existing com.google.android.apps.plus
pm install-existing com.google.android.apps.subscriptions.red
pm install-existing com.google.android.apps.tachyon
pm install-existing com.google.android.apps.youtube.music
pm install-existing com.google.android.gm
pm install-existing com.google.android.googlequicksearchbox
pm install-existing com.google.android.marvin.talkback
pm install-existing com.google.android.music
pm install-existing com.google.android.printservice.recommendation
pm install-existing com.google.android.projection.gearhead
pm install-existing com.google.android.talk
pm install-existing com.google.android.tts
pm install-existing com.google.android.videos
pm install-existing com.google.android.youtube
pm install-existing com.google.ar.core
pm install-existing com.google.vr.vrcore
pm install-existing com.gotv.nflgamecenter.us.lite
pm install-existing com.hancom.office.editor.hidden
pm install-existing com.imdb.mobile
pm install-existing com.infraware.polarisoffice5
pm install-existing com.jewelsblast.ivygames.Adventure.free
pm install-existing com.linkedin.android
pm install-existing com.logame.eliminateintruder3d
pm install-existing com.mi.android.globalFileexplorer
pm install-existing com.mi.android.globalpersonalassistant
pm install-existing com.mi.global.pocobbs
pm install-existing com.mi.global.pocostore
pm install-existing com.mi.globalbrowser
pm install-existing com.mi.globalminusscreen
pm install-existing com.micredit.in
pm install-existing com.microsoft.appmanager
pm install-existing com.microsoft.office.excel
pm install-existing com.microsoft.office.officehubrow
pm install-existing com.microsoft.office.outlook
pm install-existing com.microsoft.office.powerpoint
pm install-existing com.microsoft.office.word
pm install-existing com.microsoft.skydrive
pm install-existing com.milink.service
pm install-existing com.mintgames.triplecrush.tile.fun
pm install-existing com.mintgames.wordtrip
pm install-existing com.mipay.wallet.id
pm install-existing com.mipay.wallet.in
pm install-existing com.miui.analytics
pm install-existing com.miui.android.fashiongallery
pm install-existing com.miui.audioeffect
pm install-existing com.miui.audiomonitor
pm install-existing com.miui.bugreport
pm install-existing com.miui.carlink
pm install-existing com.miui.cit
pm install-existing com.miui.cloudbackup
pm install-existing com.miui.cloudservice
pm install-existing com.miui.cloudservice.sysbase
pm install-existing com.miui.compass
pm install-existing com.miui.contentcatcher
pm install-existing com.miui.daemon
pm install-existing com.miui.huanji
pm install-existing com.miui.hybrid
pm install-existing com.miui.hybrid.accessory
pm install-existing com.miui.maintenancemode
pm install-existing com.miui.mediaeditor
pm install-existing com.miui.mediaviewer
pm install-existing com.miui.micloudsync
pm install-existing com.miui.miservice
pm install-existing com.miui.mishare.connectivity
pm install-existing com.miui.misound
pm install-existing com.miui.msa.global
pm install-existing com.miui.nextpay
pm install-existing com.miui.notes
pm install-existing com.miui.personalassistant
pm install-existing com.miui.phrase
pm install-existing com.miui.player
pm install-existing com.miui.smsextra
pm install-existing com.miui.systemAdSolution
pm install-existing com.miui.touchassistant
pm install-existing com.miui.translation.kingsoft
pm install-existing com.miui.translation.xmcloud
pm install-existing com.miui.translation.youdao
pm install-existing com.miui.translationservice
pm install-existing com.miui.userguide
pm install-existing com.miui.videoplayer
pm install-existing com.miui.voiceassist
pm install-existing com.miui.voiceassistoverlay
pm install-existing com.miui.voicetrigger
pm install-existing com.miui.vsimcore
pm install-existing com.miui.weather2
pm install-existing com.miui.wmsvc
pm install-existing com.miui.yellowpage
pm install-existing com.mobeam.barcodeService
pm install-existing com.mobiletools.systemhelper
pm install-existing com.monotype.android.font.chococooky
pm install-existing com.monotype.android.font.cooljazz
pm install-existing com.monotype.android.font.foundation
pm install-existing com.monotype.android.font.rosemary
pm install-existing com.mygalaxy
pm install-existing com.netflix.mediaclient
pm install-existing com.netflix.partner.activation
pm install-existing com.nf.snake
pm install-existing com.nuance.swype.input
pm install-existing com.opera.browser
pm install-existing com.opera.max.oem
pm install-existing com.opera.preinstall
pm install-existing com.osp.app.signin
pm install-existing com.policydm
pm install-existing com.qti.qcc
pm install-existing com.qualcomm.uimremoteserver
pm install-existing com.sec.android.AutoPreconfig
pm install-existing com.sec.android.Preconfig
pm install-existing com.sec.android.RilServiceModeApp
pm install-existing com.sec.android.app.DataCreate
pm install-existing com.sec.android.app.SecSetupWizard
pm install-existing com.sec.android.app.SmartClipEdgeService
pm install-existing com.sec.android.app.apex
pm install-existing com.sec.android.app.applinker
pm install-existing com.sec.android.app.billing
pm install-existing com.sec.android.app.bluetoothtest
pm install-existing com.sec.android.app.chromecustomizations
pm install-existing com.sec.android.app.desktoplauncher
pm install-existing com.sec.android.app.dexonpc
pm install-existing com.sec.android.app.factorykeystring
pm install-existing com.sec.android.app.gamehub
pm install-existing com.sec.android.app.hwmoduletest
pm install-existing com.sec.android.app.kidshome
pm install-existing com.sec.android.app.magnifier
pm install-existing com.sec.android.app.myfiles
pm install-existing com.sec.android.app.ocr
pm install-existing com.sec.android.app.parser
pm install-existing com.sec.android.app.personalization
pm install-existing com.sec.android.app.popupcalculator
pm install-existing com.sec.android.app.quicktool
pm install-existing com.sec.android.app.ringtoneBR
pm install-existing com.sec.android.app.safetyassurance
pm install-existing com.sec.android.app.sbrowser
pm install-existing com.sec.android.app.servicemodeapp
pm install-existing com.sec.android.app.shealth
pm install-existing com.sec.android.app.soundalive
pm install-existing com.sec.android.app.sysscope
pm install-existing com.sec.android.app.tfunlock
pm install-existing com.sec.android.app.tourviewer
pm install-existing com.sec.android.app.translator
pm install-existing com.sec.android.app.ve.vebgm
pm install-existing com.sec.android.app.wfdbroker
pm install-existing com.sec.android.app.withtv
pm install-existing com.sec.android.app.wlantest
pm install-existing com.sec.android.cover.ledcover
pm install-existing com.sec.android.daemonapp
pm install-existing com.sec.android.desktopmode.uiservice
pm install-existing com.sec.android.diagmonagent
pm install-existing com.sec.android.easyMover
pm install-existing com.sec.android.easyMover.Agent
pm install-existing com.sec.android.easyonehand
pm install-existing com.sec.android.emergencylauncher
pm install-existing com.sec.android.mimage.avatarstickers
pm install-existing com.sec.android.mimage.gear360editor
pm install-existing com.sec.android.mimage.photoretouching
pm install-existing com.sec.android.ofviewer
pm install-existing com.sec.android.omc
pm install-existing com.sec.android.preloadinstaller
pm install-existing com.sec.android.provider.snote
pm install-existing com.sec.android.providers.security
pm install-existing com.sec.android.providers.tasks
pm install-existing com.sec.android.sdhms
pm install-existing com.sec.android.service.health
pm install-existing com.sec.android.sidesync30
pm install-existing com.sec.android.splitsound
pm install-existing com.sec.android.uibcvirtualsoftkey
pm install-existing com.sec.android.widgetapp.diotek.smemo
pm install-existing com.sec.android.widgetapp.easymodecontactswidget
pm install-existing com.sec.app.TransmitPowerService
pm install-existing com.sec.automation
pm install-existing com.sec.bcservice
pm install-existing com.sec.downloadablekeystore
pm install-existing com.sec.enterprise.knox.attestation
pm install-existing com.sec.enterprise.knox.cloudmdm.smdms
pm install-existing com.sec.enterprise.mdm.services.simpin
pm install-existing com.sec.enterprise.mdm.vpn
pm install-existing com.sec.epdgtestapp
pm install-existing com.sec.everglades
pm install-existing com.sec.everglades.update
pm install-existing com.sec.factory
pm install-existing com.sec.factory.camera
pm install-existing com.sec.factory.iris.usercamera
pm install-existing com.sec.hearingadjust
pm install-existing com.sec.kidsplat.installer
pm install-existing com.sec.knox.foldercontainer
pm install-existing com.sec.knox.knoxsetupwizardclient
pm install-existing com.sec.knox.switcher
pm install-existing com.sec.location.nsflp2
pm install-existing com.sec.mldapchecker
pm install-existing com.sec.modem.settings
pm install-existing com.sec.providers.assisteddialing
pm install-existing com.sec.readershub
pm install-existing com.sec.smartcard.manager
pm install-existing com.sec.spen.flashannotate
pm install-existing com.sec.spp.push
pm install-existing com.sec.sve
pm install-existing com.sec.usbsettings
pm install-existing com.sec.vowifispg
pm install-existing com.sec.yosemite.phone
pm install-existing com.sem.factoryapp
pm install-existing com.singtel.mysingtel
pm install-existing com.skms.android.agent
pm install-existing com.skype.raider
pm install-existing com.sohu.inputmethod.sogou.xiaomi
pm install-existing com.spotify.music
pm install-existing com.sukhavati.gotoplaying.bubble.BubbleShooter.mint
pm install-existing com.tencent.soter.soterserver
pm install-existing com.test.LTEfunctionality
pm install-existing com.touchtype.swiftkey
pm install-existing com.tripadvisor.tripadvisor
pm install-existing com.trustonic.tuiservice
pm install-existing com.unionpay.tsmservice.mi
pm install-existing com.vlingo.midas
pm install-existing com.wssnps
pm install-existing com.xiaomi.ab
pm install-existing com.xiaomi.aiasst.service
pm install-existing com.xiaomi.aiasst.vision
pm install-existing com.xiaomi.bluetooth
pm install-existing com.xiaomi.calendar
pm install-existing com.xiaomi.gamecenter.sdk.service
pm install-existing com.xiaomi.glgm
pm install-existing com.xiaomi.gnss.polaris
pm install-existing com.xiaomi.joyose
pm install-existing com.xiaomi.mi_connect_service
pm install-existing com.xiaomi.micloud.sdk
pm install-existing com.xiaomi.midrop
pm install-existing com.xiaomi.migameservice
pm install-existing com.xiaomi.mipicks
pm install-existing com.xiaomi.miplay_client
pm install-existing com.xiaomi.mircs
pm install-existing com.xiaomi.mirecycle
pm install-existing com.xiaomi.mirror
pm install-existing com.xiaomi.payment
pm install-existing com.xiaomi.powerchecker
pm install-existing com.xiaomi.simactivate.service
pm install-existing com.xiaomi.smarthome
pm install-existing com.xiaomi.xmsf
pm install-existing com.xiaomi.xmsfkeeper
pm install-existing com.zhiliaoapp.musically
pm install-existing org.mipay.android.manager
} > /dev/null 2>&1
debloat
echo "Restore Debloat HyperOs Success!!!"